
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # Start MongoDB on port 27018 internally:
    command: ["mongod", "--port", "27018"]
    # Map container's port 27018 to host's port 27018:
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  kiosk_bot:
    build: .
    container_name: kiosk_bot
    depends_on:
      - mongodb
    environment:
      - TOKEN=${TOKEN}
      - KIOSK_CHANNEL=${KIOSK_CHANNEL}
    # The bot code can be mounted, if desired:
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local